# Main Monitor
monitorv2 {
    output = eDP-1 # Laptop inbuilt
    mode = 1920x1200@60
    position = 0x0
    scale = 1
    bitdepth = 8
    cm = auto
}

# HDMI Mirror (for Projectors and the likes)
monitorv2 {
    output = HDMI-A-1	#wrong name? check with "hyprctl monitors all"
    mode = preferred
    mirror = eDP-1
    #workspacemirror = eDP-1
    scale = 1
    bitdepth = 8
    cm = auto
}
#monitorv= ,preferred, auto, 1.0
