# Main Monitor
monitorv2 {
    output = eDP-1 # Laptop inbuilt
    mode = 1920x1200@60
    position = 0x0
    scale = 1
    bitdepth = 8
    cm = auto
}

# HDMI Mirror (for Projectors and the likes)
monitorv2 {
    output = HDMI-1
    mode = preferred
    mirror = eDP-1
    scale = 1
    bitdepth = 8
    cm = auto
}
