monitorv2 {
   output = DP-3
   mode = 2560x1440@180
   position = 0x0
   scale = 1
   bitdepth = 8
   cm = auto
   #sdrbrightness = 1.22
   #sdrsaturation = 1
}

monitorv2 {
   output = HDMI-A-1
   mode = 1920x1080@120
   position = -1920x300
   scale = 1
   bitdepth = 8
   cm = auto
}

monitorv2 {
   output = DP-2
   mode = 3840x1100@60
   position = 2560x300
   scale = 1
   bitdepth = 8
   cm = auto
   transform = 3
}

# monitor = DP-3, 2560x1440@180, 0x0, 1
# monitor = HDMI-A-1, 1920x1080@120, 2560x300, 1
# monitor = DP-2, 3840x1100@60, -2560x300, 1, transform, 3

workspace = 1, monitor:DP-3, default:true #name:main,
exec-once = hyprctl dispatch focusmonitor DP-3
workspace = 2, monitor:HDMI-A-1
workspace = 3, monitor:DP-2

# input = {
#  touchdevice = {
#    output = DP-2
#  }
#}
